/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    posts: Post;
    projects: Project;
    technologies: Technology;
    users: User;
    media: Media;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface Post {
  id: number;
  title: string;
  slug: string;
  date: string;
  content: {
    [k: string]: unknown;
  }[];
  coverImage: number | Media;
  project?: number | Project;
  technologies?: number[] | Technology[];
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    medium?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    large?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    hero?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    portrait?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Project {
  id: number;
  title: string;
  slug: string;
  agencyProject?: boolean;
  projectLinks?: {
    url: string;
    linkText: string;
    id?: string;
  }[];
  description: {
    [k: string]: unknown;
  }[];
  coverImage?: number | Media;
  heading: string;
  features?: {
    feature?: string;
    image: number | Media;
    details?: string;
    id?: string;
  }[];
  content?: {
    [k: string]: unknown;
  }[];
  technologies?: number[] | Technology[];
  updatedAt: string;
  createdAt: string;
}
export interface Technology {
  id: number;
  name: string;
  logo?: number | Media;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: number;
  avatar?: number | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password: string;
}
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: number;
  name?: string;
  batch?: number;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}